knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: github
